name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version
        run: scripts/bump_version.zsh
      - name: Push changes
        run: |
          git push origin main
          git push origin --tags
